title:              CS 424 Spring '22
email:              aranga22@uic.edu
description:        Projects Hosted by Aditya Ranganathan 
author:             Aditya Ranganathan
baseurl:            ""
url:                "https://adi-r.github.io"

# Social Profiles
twitter_username:   
github_username:    adi-r
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
